### ISSUE TITLE
Failed to install python packages

### ISSUE THREAD

**Issue by yurko006** [awslabs/eb-locustio-sample#15]
Hey everyone,

When deploying this environment, I ran into the following issue from the eb-activity.log file: 

[2018-01-30T19:22:46.843Z] INFO  [6266]  - [Application update eb-locustio-working-quad-client@84/AppDeployStage0/EbExtensionPreBuild/Infra-EmbeddedPreBuild/prebuild_0_eb_locustio] : Completed activity.
[2018-01-30T19:22:46.843Z] INFO  [6266]  - [Application update eb-locustio-working-quad-client@84/AppDeployStage0/EbExtensionPreBuild/Infra-EmbeddedPreBuild] : Activity execution failed, because: Could not successfully install python packages (return code 1) (ElasticBeanstalk::ExternalInvocationError)

[2018-01-30T19:22:46.843Z] INFO  [6266]  - [Application update eb-locustio-working-quad-client@84/AppDeployStage0/EbExtensionPreBuild/Infra-EmbeddedPreBuild] : Activity failed.
[2018-01-30T19:22:49.092Z] INFO  [6266]  - [Application update eb-locustio-working-quad-client@84/AppDeployStage0/EbExtensionPreBuild] : Activity failed.
[2018-01-30T19:22:49.092Z] INFO  [6266]  - [Application update eb-locustio-working-quad-client@84/AppDeployStage0] : Activity failed.
[2018-01-30T19:22:49.092Z] INFO  [6266]  - [Application update eb-locustio-working-quad-client@84] : Completed activity. Result:
  Application update - Command CMD-AppDeploy failed
[2018-01-30T19:25:33.320Z] INFO  [6429]  - [CMD-BundleLogs] : Starting activity...
[2018-01-30T19:25:33.320Z] INFO  [6429]  - [CMD-BundleLogs/AddonsBefore] : Starting activity...
[2018-01-30T19:25:33.320Z] INFO  [6429]  - [CMD-BundleLogs/AddonsBefore] : Completed activity.
[2018-01-30T19:25:33.320Z] INFO  [6429]  - [CMD-BundleLogs/BundleLogs] : Starting activity...
[2018-01-30T19:25:33.320Z] INFO  [6429]  - [CMD-BundleLogs/BundleLogs/BundleLogs] : Starting activity...

I was wondering if anyone has ran into something similar, and what you did to solve this issue. It seems strange to me though, that it was working fine, and as soon as I upgraded to the latest version of this repo, I started experiencing issues pertaining to the former.

**Comment by yurko006** [comment]
I think I fixed this issue by removing pyzmq from the setup.config file in .ebextensions. I think that requirement is already satisfied by locust.

**Comment by yurko006** [comment]
Nevermind, that worked on one deployment but failed for subsequent ones. Please advise.

**Comment by ianseyer** [comment]
Also having this error on a vanilla install.

```
WARNING: You have uncommitted changes.
Creating application version archive "app-1485-180131_184252".
Uploading eb-locustio-sample/app-1485-180131_184252.zip to S3. This may take a while.
Upload Complete.
INFO: Environment update is starting.
INFO: Deploying new version to instance(s).
ERROR: [Instance: i-052e4fd9a0e87f39a] Command failed on instance. Return code: 1 Output: Could not successfully install python packages (return code 1).
EBExtension failed. For more detail, check /var/log/eb-activity.log using console or EB CLI.
INFO: Command execution completed on all instances. Summary: [Successful: 0, Failed: 1].
ERROR: Unsuccessful command execution on instance id(s) 'i-052e4fd9a0e87f39a'. Aborting the operation.
ERROR: Failed to deploy application.

ERROR: ServiceError - Failed to deploy application.
```

**Comment by abhiksingh** [comment]
This issue appears to be a package problem. The Python dependencies transitively bring in the gevent package, which had a release a few days ago (1.3a1) and now fails to install. I believe that root error is:
 
sudo easy_install locustio==0.8.1 pyzmq==16.0.3
….
  File "/tmp/easy_install-YWhRvZ/gevent-1.3a1/setup.py", line 44, in <module>
  File "/tmp/easy_install-YWhRvZ/gevent-1.3a1/_setuplibev.py", line 94, in <module>
  File "/tmp/easy_install-YWhRvZ/gevent-1.3a1/_setuputils.py", line 168, in cythonize1
TypeError: cythonize() got an unexpected keyword argument 'include_path'
 
This is most likely related to https://github.com/gevent/gevent/issues/1083.

One option for fixing this is to pin the gevent package to a previous version in .ebextensions/options.config by adding ‘gevent: [ "1.2.2" ]’ under Python packages.

**Comment by yurko006** [comment]
Do you mean setup.config and not options.config?

**Comment by ianseyer** [comment]
I have dropped the `python:` element and replaced it with a `command:` that simply `pip install[s] locustio` and it works.

**Comment by yurko006** [comment]
@ianseyer Can you show me what the commands section of your setup.config file looks like? Or at least the portion which works.

**Comment by ianseyer** [comment]
```
packages:
  yum:
    gcc-c++: []

option_settings:
  aws:elasticbeanstalk:application:environment:
    MASTER_IP_TABLE: '`{ "Ref" : "MasterIPTable"}`'
    EB_ENV_NAME: '`{"Ref" : "AWSEBEnvironmentName"}`'

commands:
  install_locustio:
    command: "pip install locustio"
  create_home_dir:
    command: "mkdir /home/webapp | chown webapp:webapp /home/webapp"
  copy_deploy_manifest:
    command: "cp /opt/elasticbeanstalk/deploy/manifest /tmp/; chmod 777 /tmp/manifest"

files:
  # add configuration to display the locust log files when tailing logs
  "/opt/elasticbeanstalk/tasks/taillogs.d/locustio.conf":
    owner: root
    group: root
    mode: "000644"
    content: |
      /var/log/locust-master*.log
      /var/log/locust-follower*.log
```
